### ISSUE TITLE
Real-time alert of already-present user

### ISSUE THREAD

**Issue by DamuelOnline** [seancallaway/SubredditLog#24]
**What is missing?**
An alert under the submission cell for the user to receive moderator action which appears without submitting the name. Could include rule broken, date, and moderator action. 

Perhaps a version of the same alert that scans notes for mentions of the user. 

A separate alert for both. 

**Why do we need it?**
The severity of a moderator action on a user often depends on whether it is a first offense. As it stands, before moderation, a mod must check the whole mod log before acting. Whether or not the user has appeared before, the mod then ends up on the submission page. 

With this feature, users could reliably use the submission page as a first step. If, as in most cases, the user being moderated upon is not present elsewhere in the log, the mod will know they need not search further for information.

**Comment by seancallaway** [comment]
This should use an AJAX check and, if the username has been found display a string in the field errors area with the following format:

```
{{user.username}} has {{qty}} entries in the modlog. <a target="_blank" href="...">Click here</a> to see them.
```

The link should take the user to a search results page for that username.

**Comment by seancallaway** [comment]
[This](https://htmx.org/examples/inline-validation/) may be an ideal solution.
